### ISSUE TITLE
npm install fails...

### ISSUE THREAD

**Issue by zen-tmq** [MiguelMadero/import-from-npm#1]
(venv) [16:44:24 ~/Documents/zenefits/yourPeople3/client-app] ember install ember-cli-import-from-npm
Installed packages for tooling via npm.
Cannot find module 'broccoli-source'
Error: Cannot find module 'broccoli-source'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/dhoyer/Documents/zenefits/yourPeople3/client-app/node_modules/ember-cli-import-from-npm/index.js:5:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Does not look like the addon fully installs. Certainly node_modules is unpopulated. Also, trying to do anything after this failed install, like `ember serve` reshows the error

**Comment by MiguelMadero** [comment]
Thanks for reporting it. I fixed it and released 0.1.4.
